worker_processes auto;

events { worker_connections 8192; }

http {
  upstream gateway_upstream {
    server gateway:3000;
  }

  server {
    listen 80;

    location /increment/ {
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /count/ {
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
    }

    location /health {
      proxy_pass http://gateway_upstream;
    }
  }
}
